name: Build

on: [push]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.3"
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme TextureSwiftSupport -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.2'
