name: CocoaPods

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.4"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
